apiVersion: apps/v1
kind: Deployment
metadata:
  name: estate-backend-app
  labels:
    app: estate-backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: estate-backend-app
  template:
    metadata:
      labels:
        app: estate-backend-app
    spec:
      containers:
      - name: estate-backend-app
        image: farmanahmed888/estate-backend:latest
        ports:
        - containerPort: 8080